nginx_vhosts:
  - listen: "80 default_server"
    server_name: app.test
    extra_parameters: |
      location / {
        proxy_pass http://0.0.0.0:5601;
        proxy_set_header Authorization "";
        proxy_read_timeout 90s;
      }

elk_version: "{{ lookup('env', 'ELK_VERSION') or '8.2.2' }}"

filebeat_inputs:
  - type: log
    paths:
      - /var/log/nginx/access.log
      - /var/log/nginx/error.log
