- name: Check, if filebeat is installed
  stat:
    path: "/usr/share/filebeat-{{ elk_version }}-linux-x86_64"
  register: filebeat_path

- name: Download & Extract filebeat, if not installed
  unarchive:
    src: "https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-{{ elk_version }}-linux-x86_64.tar.gz"
    dest: /usr/share
    remote_src: yes
    mode: "0741"
  when: not filebeat_path.stat.exists

- name: Create filebeat symlink in /usr/bin
  file:
    src: "/usr/share/filebeat-{{ elk_version }}-linux-x86_64/filebeat"
    dest: /usr/local/bin/filebeat
    state: link

- name: Create filebeat.yml template
  template:
    src: templates/filebeat.yml.j2
    dest: /usr/share/filebeat-{{ elk_version }}-linux-x86_64/filebeat.yml
    mode: "0644"
    owner: root
    validate: "filebeat test config -c %s"

- name: Create filebeat service, if not existing
  template:
    src: templates/filebeat.service.j2
    dest: /etc/systemd/system/filebeat.service
    owner: root

- name: Enable and start filebeat service, if not running
  service:
    name: "filebeat"
    state: started
    enabled: yes
