- name: Pull kibana image, if version '{{ elk_version }}' not present
  community.docker.docker_image:
    name: "{{ kibana_image }}"
    source: pull

- name: Start kibana container, if not running
  community.docker.docker_container:
    name: "{{ kibana_container }}"
    image: "{{ kibana_image }}"
    published_ports: 5601:5601
    networks:
      - name: "{{ docker_network }}"
    env:
      ELASTIC_SEARCH_HOSTS: http://elasticsearch:9200
    state: started
