nginx_user: www-data
nginx_vhosts:
  - listen: "80 default_server"
    server_name: logs.test
    extra_parameters: |
      location / {
        proxy_pass http://0.0.0.0:5601;
        proxy_set_header Authorization "";
        proxy_read_timeout 90s;
      }

elk_version: 8.2.2
elastic_default_password: "{{ lookup('env', 'ELASTIC_DEFAULT_PASSWORD') }}"
docker_network: elk_network
